# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to the App Store"
  lane :release do
#    sync_code_signing
    build_app(scheme: "HR")
#    build_app(export_xcargs: "-allowProvisioningUpdates")
#    enable_automatic_code_signing(path: "HR.xcodeproj")
    build_app(export_xcargs: "-allowProvisioningUpdates")
    upload_to_app_store
  end
 
 desc "Push a beta build to the local" 
 lane :beta do
   build_app(export_xcargs: "-allowProvisioningUpdates")
  end
end
